# Generated by Django 4.1 on 2022-08-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth",
            field=models.DateField(null=True, verbose_name="생년월일"),
        ),
    ]
