# Generated by Django 4.1 on 2022-08-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writers", "0002_alter_writer_approval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writer",
            name="approval",
            field=models.BooleanField(default=False, verbose_name="작가등록여부"),
        ),
    ]
