# Generated by Django 4.1 on 2022-08-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writers", "0003_alter_writer_approval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writer",
            name="approval",
            field=models.BooleanField(default=False),
        ),
    ]
