# Generated by Django 4.0.6 on 2022-08-25 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0005_alter_writer_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='painting',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='writers.painting'),
        ),
    ]
